"""initial migration (autogenerated)

Revision ID: 10d02edfa1d3
Revises: 
Create Date: 2026-04-23 14:03:31.720993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '10d02edfa1d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('batch_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('total_new', sa.Integer(), nullable=True),
    sa.Column('total_dormant', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('processed_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('failed_lead_ids', sa.Text(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_runs_status'), ['status'], unique=False)

    op.create_table('blacklisted_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('blacklisted_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blacklisted_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blacklisted_tokens_token'), ['token'], unique=True)

    op.create_table('communications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('internal_message_ref', sa.String(length=200), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('email_number', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=30), nullable=True),
    sa.Column('sent_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('delivered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('opened_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('clicked_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('bounced_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('unsubscribed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('clicked_cta_url', sa.String(length=500), nullable=True),
    sa.Column('clicked_cta_label', sa.String(length=100), nullable=True),
    sa.Column('campaign_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communications_internal_message_ref'), ['internal_message_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_communications_lead_id'), ['lead_id'], unique=False)

    op.create_table('consultation_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('form_id', sa.String(length=20), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('request_type', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=5), nullable=True),
    sa.Column('date_of_birth', sa.String(length=20), nullable=True),
    sa.Column('prefecture', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('face_to_face', sa.Boolean(), nullable=True),
    sa.Column('email_captured', sa.Boolean(), nullable=True),
    sa.Column('campaign_code', sa.String(length=100), nullable=True),
    sa.Column('contract_status', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('assigned_advisor', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('scheduled_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consultation_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultation_requests_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultation_requests_request_id'), ['request_id'], unique=False)

    op.create_table('email_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('communication_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('score_delta', sa.Float(), nullable=True),
    sa.Column('clicked_url', sa.String(length=500), nullable=True),
    sa.Column('clicked_label', sa.String(length=100), nullable=True),
    sa.Column('email_number', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('campaign_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_events_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_events_communication_id'), ['communication_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_events_lead_id'), ['lead_id'], unique=False)

    op.create_table('email_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=5), nullable=False),
    sa.Column('persona_code', sa.String(length=20), nullable=True),
    sa.Column('product_code', sa.String(length=50), nullable=True),
    sa.Column('template_name', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('keigo_level', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_templates_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('hitl_queue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=100), nullable=False),
    sa.Column('gate_type', sa.String(length=10), nullable=False),
    sa.Column('gate_description', sa.String(length=200), nullable=True),
    sa.Column('draft_subject', sa.String(length=500), nullable=True),
    sa.Column('draft_body', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=30), nullable=True),
    sa.Column('email_number', sa.String(length=10), nullable=True),
    sa.Column('handoff_briefing', sa.Text(), nullable=True),
    sa.Column('handoff_score_snapshot', sa.Float(), nullable=True),
    sa.Column('suggested_persona', sa.String(length=20), nullable=True),
    sa.Column('persona_confidence', sa.Float(), nullable=True),
    sa.Column('campaign_batch_size', sa.String(length=50), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('edited_subject', sa.String(length=500), nullable=True),
    sa.Column('edited_body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('reviewed_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hitl_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hitl_queue_gate_type'), ['gate_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_hitl_queue_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hitl_queue_review_status'), ['review_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_hitl_queue_thread_id'), ['thread_id'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quote_id', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('date_of_birth', sa.String(length=20), nullable=True),
    sa.Column('ans3', sa.String(length=5), nullable=True),
    sa.Column('ans4', sa.String(length=5), nullable=True),
    sa.Column('ans5', sa.String(length=5), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('banner_code', sa.String(length=100), nullable=True),
    sa.Column('product_code', sa.String(length=50), nullable=True),
    sa.Column('plan_code', sa.String(length=50), nullable=True),
    sa.Column('registration_source', sa.String(length=50), nullable=True),
    sa.Column('opt_in', sa.Boolean(), nullable=True),
    sa.Column('accept_mail_error', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=200), nullable=True),
    sa.Column('scenario_id', sa.String(length=5), nullable=True),
    sa.Column('persona_code', sa.String(length=20), nullable=True),
    sa.Column('persona_confidence', sa.Float(), nullable=True),
    sa.Column('keigo_level', sa.String(length=20), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('base_score', sa.Float(), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('current_agent_node', sa.String(length=30), nullable=True),
    sa.Column('emails_sent_count', sa.Integer(), nullable=True),
    sa.Column('max_emails', sa.Integer(), nullable=True),
    sa.Column('revival_segment', sa.String(length=5), nullable=True),
    sa.Column('cooldown_flag', sa.Boolean(), nullable=True),
    sa.Column('is_converted', sa.Boolean(), nullable=True),
    sa.Column('workflow_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('thread_id', sa.String(length=100), nullable=True),
    sa.Column('commit_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_active_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index('idx_lead_scenario', ['scenario_id'], unique=False)
        batch_op.create_index('idx_lead_status', ['workflow_status'], unique=False)
        batch_op.create_index('idx_lead_thread', ['thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_last_active_at'), ['last_active_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_quote_id'), ['quote_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_leads_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_workflow_completed'), ['workflow_completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_workflow_status'), ['workflow_status'], unique=False)

    op.create_table('quotes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('product_code', sa.String(length=50), nullable=True),
    sa.Column('premium_estimate_jpy', sa.Integer(), nullable=True),
    sa.Column('raw_quote_ref', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotes_lead_id'), ['lead_id'], unique=False)

    op.create_table('scenarios_config',
    sa.Column('scenario_id', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('handoff_threshold', sa.Float(), nullable=False),
    sa.Column('base_score', sa.Float(), nullable=False),
    sa.Column('cadence_days', sa.Integer(), nullable=False),
    sa.Column('max_emails', sa.Integer(), nullable=False),
    sa.Column('default_keigo', sa.String(length=20), nullable=True),
    sa.Column('default_tone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('scenario_id')
    )
    op.create_table('sse_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('lead_id', sa.String(length=100), nullable=True),
    sa.Column('thread_id', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sse_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sse_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sse_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sse_events_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sse_events_thread_id'), ['thread_id'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('custom_permissions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_user_email', ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_user_email')

    op.drop_table('users')
    with op.batch_alter_table('sse_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sse_events_thread_id'))
        batch_op.drop_index(batch_op.f('ix_sse_events_lead_id'))
        batch_op.drop_index(batch_op.f('ix_sse_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_sse_events_created_at'))

    op.drop_table('sse_events')
    op.drop_table('scenarios_config')
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotes_lead_id'))

    op.drop_table('quotes')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_workflow_status'))
        batch_op.drop_index(batch_op.f('ix_leads_workflow_completed'))
        batch_op.drop_index(batch_op.f('ix_leads_thread_id'))
        batch_op.drop_index(batch_op.f('ix_leads_session_id'))
        batch_op.drop_index(batch_op.f('ix_leads_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_leads_quote_id'))
        batch_op.drop_index(batch_op.f('ix_leads_last_active_at'))
        batch_op.drop_index(batch_op.f('ix_leads_email'))
        batch_op.drop_index('idx_lead_thread')
        batch_op.drop_index('idx_lead_status')
        batch_op.drop_index('idx_lead_scenario')

    op.drop_table('leads')
    with op.batch_alter_table('hitl_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hitl_queue_thread_id'))
        batch_op.drop_index(batch_op.f('ix_hitl_queue_review_status'))
        batch_op.drop_index(batch_op.f('ix_hitl_queue_lead_id'))
        batch_op.drop_index(batch_op.f('ix_hitl_queue_gate_type'))

    op.drop_table('hitl_queue')
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_templates_scenario_id'))

    op.drop_table('email_templates')
    with op.batch_alter_table('email_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_events_lead_id'))
        batch_op.drop_index(batch_op.f('ix_email_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_email_events_communication_id'))
        batch_op.drop_index(batch_op.f('ix_email_events_campaign_id'))

    op.drop_table('email_events')
    with op.batch_alter_table('consultation_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultation_requests_request_id'))
        batch_op.drop_index(batch_op.f('ix_consultation_requests_lead_id'))

    op.drop_table('consultation_requests')
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communications_lead_id'))
        batch_op.drop_index(batch_op.f('ix_communications_internal_message_ref'))

    op.drop_table('communications')
    with op.batch_alter_table('blacklisted_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blacklisted_tokens_token'))

    op.drop_table('blacklisted_tokens')
    with op.batch_alter_table('batch_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_runs_status'))

    op.drop_table('batch_runs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
