"""remove_language_preference

Revision ID: 513b87b07032
Revises: 4f6d36a665f9
Create Date: 2026-04-18 18:21:42.340651

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "513b87b07032"
down_revision: Union[str, Sequence[str], None] = "4f6d36a665f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("language_preference")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "language_preference",
                sa.VARCHAR(length=5),
                server_default=sa.text("'JA'"),
                nullable=True,
            )
        )

    # ### end Alembic commands ###
